name: Daily Update Nuclei POCs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Clone Repos
      run: python 1-clone_repos.py
    - name: Move Duplicated
      run: python 2-remove_duplicated.py
    - name: Get POC Name
      run: python 3-get_pocname.py
      
    - name: Commit and Push changes
      run: |
        echo $(date +'%Y%m%d') > date.txt
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "$(date +'%Y%m%d')"
        git push -v --progress
